_BASE_: ../Base-MGN.yml

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]


MODEL:
  BACKBONE:
    WITH_IBN: True
    #PRETRAIN_PATH: '/mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/zhouxiao/research/fast-reid-master-mixstyle/pretrained/resnet50_ibn_a-d9d0bb7b.pth'
    PRETRAIN_PATH: '/mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/zhouxiao/research/fast-reid-master-mixstyle/pretrained/lupws_r50.pth'
    NORM: BN #for 1 GPU


  LOSSES:
    NAME: ( "CrossEntropyLoss",  "MaxCone", )  #"SupConLoss", ) #, "MoCoLoss", "MaxCone")  #default ("CrossEntropyLoss","TripletLoss",)

    MAXCONE:
      SCALE: 1.0
      TEMP: 0.05
      TYPE: 'adaptive'
      
  HEADS:
    NORM: BN #for 1 GPU
    NECK_FEAT: after
    POOL_LAYER: GeneralizedMeanPoolingP
    CLS_LAYER: CircleSoftmax  # CircleSoftmax
    SCALE: 64  #64
    MARGIN: 0.35   #0.35
    CLS_ENABLE: True  # True
    EMBEDDING_DIM: 256

DATALOADER:
  NUM_INSTANCE: 16  ## default 16

SOLVER:
  BASE_LR: 0.00035  ## default 0.00035
  IMS_PER_BATCH: 64   ## default 64
  WARMUP_ITERS: 2000 ## default 2000

  FREEZE_ITERS: 1000  ## default 1000


DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/zhouxiao/research/fast-reid-master-mixstyle/logs/market1501/lup_mgn_circle_L1_adaptive_weight_sim
