_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]


MODEL:
  BACKBONE:
    WITH_IBN: False
    PRETRAIN_PATH: '/mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/zhouxiao/research/fast-reid-master-mixstyle/pretrained/resnet50_ibn_a-d9d0bb7b.pth'
    NORM: BN #for 1 GPU
  
  LOSSES:
    NAME: ( "CrossEntropyLoss",  "TripletLoss", ) #, "MoCoLoss", "MaxCone")  #default ("CrossEntropyLoss","TripletLoss",)
   
    TRI:
      HARD_MINING: True
      NORM_FEAT: False
      MARGIN: 0.0

    MAXCONE:
      SCALE: 0.1
      TEMP: 0.04
      TYPE: 'adaptive'

  HEADS:
    NORM: BN #for 1 GPU
    NECK_FEAT: after
    POOL_LAYER: GeneralizedMeanPoolingP
    CLS_LAYER: Linear  # CircleSoftmax
    SCALE: 1  #64
    MARGIN: 0.   #0.35
    CLS_ENABLE: True  # True
    #EMBEDDING_DIM: 256   

DATALOADER:
  NUM_INSTANCE: 8  ## default 16

SOLVER:
  BASE_LR: 0.00035  ## default 0.00035
  IMS_PER_BATCH: 128   ## default 64
  WARMUP_ITERS: 1000 ## default 2000
  FREEZE_ITERS: 500  ## default 1000


DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/zhouxiao/research/fast-reid-master-mixstyle/logs/market1501/norm_CE_triplet_input256_noibn
