_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True
    NORM: BN 
    PRETRAIN_PATH: '/mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/zhouxiao/research/fast-reid-master-mixstyle/pretrained/resnet50_ibn_a-d9d0bb7b.pth'

  HEADS:
    POOL_LAYER: GeneralizedMeanPooling
    NORM: BN 
    CLS_ENABLE: True  # default True
    NECK_FEAT: after

  LOSSES:
    NAME: ( "CrossEntropyLoss", "MaxCone", ) #("TripletLoss", )  #"CrossEntropyLoss",
    TRI:
      HARD_MINING: False
      MARGIN: 0.0
    MAXCONE:
      SCALE: 0.5
      TEMP: 0.05
      TYPE: 'adaptive'


DATASETS:
  NAMES: ("VehicleID",)
  TESTS: ("SmallVehicleID", "MediumVehicleID", "LargeVehicleID",)

DATALOADER:
  NUM_INSTANCE: 8

SOLVER:
  BIAS_LR_FACTOR: 1.

  IMS_PER_BATCH: 512
  MAX_EPOCH: 120
  STEPS: [30, 70, 90]
  WARMUP_ITERS: 2000  # default 2000 for bs-512 

  CHECKPOINT_PERIOD: 20

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128

OUTPUT_DIR: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/zhouxiao/research/fast-reid-master-mixstyle/logs/vehicleid/norm_CE_L1_adaptive_ins8_d5_t05_120e_copy4
