_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  META_ARCHITECTURE: Baseline  # default Baseline
  NUM_FEAT_PER_ID: 1

  BACKBONE:
    WITH_IBN: True
    NORM: BN

    PRETRAIN_PATH: '/mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/zhouxiao/research/fast-reid-master-mixstyle/pretrained/resnet50_ibn_a-d9d0bb7b.pth'
  HEADS:
    POOL_LAYER: GeneralizedMeanPooling
    NORM: BN 
    CLS_LAYER: Linear  #default Linear.   CircleSoftmax
    SCALE: 1   #default 1  64 for circle
    MARGIN: 0.  #default 0.  0.35 for circle
    CLS_ENABLE: True  # default True

  LOSSES:
    NAME: ( "CrossEntropyLoss","MaxCone" )  #default "CrossEntropyLoss", "TripletLoss", "MaxCone", "MoCoLoss"
    TRI:
      HARD_MINING: False
      MARGIN: 0.0
      SCALE: 1.0
    MOCO:
      SCALE: 1.0
      TYPE: "triplet"
    MAXCONE:
      SCALE: 1.0
      TEMP: 0.05
    CE:
      SCALE: 1.0
    MULTINCE:
      SCALE: 1.0


DATASETS:
  NAMES: ("VehicleID",)
  TESTS: ("SmallVehicleID", "MediumVehicleID", "LargeVehicleID","VeRi")

SOLVER:
  BIAS_LR_FACTOR: 1.

  IMS_PER_BATCH: 512  # default 512 
  MAX_EPOCH: 60
  STEPS: [30, 50]
  WARMUP_ITERS: 2000  # default 2000 for bs-512 

  CHECKPOINT_PERIOD: 20

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128

OUTPUT_DIR: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/zhouxiao/research/fast-reid-master-mixstyle/logs/vehicleid/norm_CE_L1_05
