_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL :

  META_ARCHITECTURE: Baseline  # default Baseline
  NUM_FEAT_PER_ID: 1

  BACKBONE:
    NAME: build_resnet_backbone  # with mixstyle  # build_resnet_backbone (without mixstyle)
    WITH_IBN: True
    WITH_NL: False  # default True

    NORM: BN #for 1 GPU
    PRETRAIN: True  # load imagenet pretrained backbone resnet-50
    
    PRETRAIN_PATH: '/mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/zhouxiao/research/fast-reid-master-mixstyle/pretrained/resnet50_ibn_a-d9d0bb7b.pth'

    EXTRA_BN: False  # finetune for MOT20 pretrained model

  HEADS:
    NORM: BN  # syncBN for multi-GPU
    CLS_ENABLE: False  # default True
    EMBEDDING_DIM: 0  # default 0
    WITH_BNNECK: True

    CLS_LAYER: Linear
    SCALE: 1
    MARGIN: 0.

  LOSSES:
    NAME: ( "MaxCone", ) # "CircleLoss", "TripletLoss", "CrossEntropyLoss", "MoCoLoss" ) #"MaxCone")  #default ("CrossEntropyLoss","TripletLoss",)
    TRI:
      NORM_FEAT: False  # default False
      SCALE: 1.
      HARD_MINING: True
      
    MAXCONE:
      SCALE: 1.0
      TEMP: 0.05
      TYPE: 'all_he'

    CIRCLE:
      SCALE: 1.0


SOLVER:
  #OPT: SGD
  BASE_LR: 0.00035  # default 0.01
  #ETA_MIN_LR: 7.7e-5  #default 7.7e-5

  IMS_PER_BATCH: 128   # 64 for finetune, 256 for pretraining
  MAX_EPOCH: 60  # 60 for finetune, 200 for pretraining
  WARMUP_ITERS: 1500
  FREEZE_ITERS: 1500  # 3000 for finetune, 0 for pretraining
  DELAY_EPOCHS: 30

  CHECKPOINT_PERIOD: 10

DATASETS:
  NAMES: ( "VeRi",) # "BDD")
  TESTS: ( "VeRi", ) #"SmallVehicleID", "MediumVehicleID", "LargeVehicleID",)

DATALOADER:
  NUM_INSTANCE: 32
  SAMPLER_TRAIN: BalancedIdentitySampler

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256

OUTPUT_DIR: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/zhouxiao/research/fast-reid-master-mixstyle/logs/veri/norm_single_all_he_128_32
